### ISSUE TITLE
Server login timeouts are not detected or handled

### ISSUE THREAD

**Issue by goneall** [fossology/fossdriver#44]
It looks like if the session expires, the `server._get(...)` function will appear to succeed when in fact it will return a message `Module unavailable or your login session timed out.`

**Comment by goneall** [comment]
I was thinking this could be fixed, at least for the `_get` method by checking specifically for the login failure text then re-login and retry the get.

I'm not sure if the same solution would work with `_post`.

Let me know if you would be interested in a pull request with the above proposed fix.

**Comment by swinslow** [comment]
Hi @goneall -- I'm not regularly using or developing fossdriver anymore, but happy to take and merge a PR for this fix.

I think the approach you described makes sense. A few quick thoughts:
1. On the re-login, I'm not certain whether `self.session` would need to be replaced with a new `requests.Session()`. It's been long enough since I wrote this code that I don't recall, unfortunately, but if it isn't working as expected with the change then that may be one thing to check.
2. If the solution doesn't seem to work with `_post`, maybe a (very hacky) alternative could be to insert into the `_post()` function a preliminary call to a standard endpoint via `_get()` which could do the re-login check before the actual POST call is made.
3. I assume there should be some limit to the number of login retries -- perhaps a parameter that could be set in the `FossConfig` object? Something at least to make sure that a failing call doesn't get stuck in an infinite login retry loop.

Thanks for being willing to look into this!

**Comment by swinslow** [comment]
Fixed in #46, thanks @goneall!
